### ISSUE TITLE
rpi-zero wiring diagram

### ISSUE THREAD

**Issue by siffland** [MiSTeX-devel/MiSTeX-hardware#3]
Is there an updated diagram or pinout how you are attaching the rpi-zero to the FPGA boards, preferably the qmtech boards.

Thanks,
Sean

**Comment by hansfbaier** [comment]
Hi, the Pin assignments can be found in the
python build files in MiSTeX-boards:
![image](https://github.com/MiSTeX-devel/MiSTeX-hardware/assets/148607/eea3227b-9b3b-425d-9ee6-c806567e1ec3)
You need to wire up those to the SPI0 and the four GPIO lines I configured in the MainMiSTeX binary.
I didn't have the time to do it myself, my paid work is rather demanding at the moment.
Here are the Pin assignments:
![image](https://github.com/MiSTeX-devel/MiSTeX-hardware/assets/148607/199cf3d3-1ec9-4b59-a263-b62d0fe51ac1)

**Comment by hansfbaier** [comment]
https://pinout.xyz/pinout/pin15_gpio22/

**Comment by hansfbaier** [comment]
![2023-11-07_10-41](https://github.com/MiSTeX-devel/MiSTeX-hardware/assets/148607/bd49ac04-3cef-45c7-bc82-96a527a0d3cd)

**Comment by hansfbaier** [comment]
![image](https://github.com/MiSTeX-devel/MiSTeX-hardware/assets/148607/2e73a808-b7a4-495d-a1b5-7b27b0a97bc1)

**Comment by hansfbaier** [comment]
OK, added this information to the README, closing this issue:
https://github.com/MiSTeX-devel/MiSTeX-hardware/blob/main/README.md
