### ISSUE TITLE
QMTech hardware

### ISSUE THREAD

**Issue by DFL1973** [MiSTeX-devel/MiSTeX-hardware#4]
Hello, I just saw the PCB for QMtech that you added a few days ago. Is it working already or is it just an untested concept?
Thanks for sharing, you are doing a great job!

**Comment by hansfbaier** [comment]
Hi, I will find out tomorrow or on Monday, when the boards arrive at my home.

**Comment by hansfbaier** [comment]
Hi it is working!
You can order rev2, and see the picture in the README, I just updated it.
