### ISSUE TITLE
MiSTeX coming along

### ISSUE THREAD

**Issue by magwed** [MiSTeX-devel/MiSTeX-hardware#5]
Nice to see that this is still in development. Where is the general channel for chatting/sharing info about MiSTeX? I can't see any discussion forum here, there is no facebook group and I can't find anything in Discord. Are there anything hidden that I can get myself invited to or is this a closed project right now? I'm really interested in seeing where this can lead, what tool chains that are used, how the hardware currently are working, which hardware is used, what's next? Thanks!

**Comment by no-shad** [comment]
On the patreon there was an invite to a group posted but I found it to be expired when I tried to join

**Comment by hansfbaier** [comment]
@magwe @no-shad I updated the Link on Patreon: Here is the invite:
https://t.me/+kuN3TVEjBSAxMDg0
