### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by tomaszb-dev** [MiSTeX-devel/MiSTeX-hardware#8]
Hello,
So i acquired the xillinx fpga board and ordered MisteX pcb. Maybe it's me but I cannot find any BOM for the parts.

**Comment by hansfbaier** [comment]
Hello,
the complete production files including the BOM are here:
https://github.com/MiSTeX-devel/MiSTeX-hardware/tree/main/QMTech-MiSTeX/jlcpcb/production_files

They are actually complete for JLCPCB assembly, so you can have the complete board made there for comparatively
little money.

Also in the Telegram community chat there are several people who still have spare boards to sell.
I am closing this issue, please comment below if you have further questions.

**Comment by tomaszb-dev** [comment]
Hello,
JLCPB asked me 350USD for assembly :D Each time a different price but not less than 350USD
I'm trying now with PCBWay. Anyway, as I can see it's a 2 layer board, but PCB way is asking me if it's a 4 layers one... Or really it's a 4 layer one?

**Comment by hansfbaier** [comment]
No it is a 4 layer board

**Comment by hansfbaier** [comment]
Please ask in the community chat,
several members have an assembled board to sell
https://t.me/+kuN3TVEjBSAxMDg0

That will be much cheaper (40 Euro or so)

**Comment by tomaszb-dev** [comment]
By the way will you open a channel on discord?
"That will be much cheaper (40 Euro or so)." 
Maybe I will do so. However I already ordered 5 PCBs. I will have to solder them. It will be a lot of resistors and caps :D

**Comment by tomaszb-dev** [comment]
That will be much cheaper (40 Euro or so). Maybe I will do so. However I already ordered 5 PCBs. I will have to solder them. It will be a lot of resistors and caps :D
